name: Publish Workshop Material
on:
  push:
    branches:
      - main
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.5.1
      - name: Build Walnut
        run: gradle clean customFatJar
      - name: Package Walnut
        run:  zip -r walnut.zip walnut.sh build/libs/Walnut-all.jar Automata\ Library/ Result/ Command\ Files/ Macro\ Library/ Word\ Automata\ Library/ Custom\ Bases/ Morphism\ Library/ Help\ Documentation/ Transducer\ Library/
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          files: walnut.zip
